<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="trolls" nsURI="http://www.example.org/trolls" nsPrefix="trolls">
  <eClassifiers xsi:type="ecore:EClass" name="Match">
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbols" upperBound="-1"
        eType="#//Symbol" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conveyorBelt" eType="#//ConveyorBelt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="board" eType="#//Board"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConveyorBelt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conveyorBeltSymbolEntries"
        upperBound="-1" eType="#//ConveyorBeltSymbolEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characterID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"
        defaultValueLiteral="'0'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Board">
    <eOperations name="addBoardSymbolEntry">
      <eParameters name="boardSymbolEntry" eType="#//BoardSymbolEntry"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boardSymbolEntries" upperBound="-1"
        eType="#//BoardSymbolEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConveyorBeltSymbolEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbol" eType="#//Symbol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoardSymbolEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbol" eType="#//Symbol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trollID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
</ecore:EPackage>
